//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEP.BusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AEPEntities : DbContext
    {
        public AEPEntities()
            : base("name=AEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AEPGroup> AEPGroup { get; set; }
        public virtual DbSet<AEPGroupUser> AEPGroupUser { get; set; }
        public virtual DbSet<DocAlert> DocAlert { get; set; }
        public virtual DbSet<DocRecord> DocRecord { get; set; }
        public virtual DbSet<DocRecord_H> DocRecord_H { get; set; }
        public virtual DbSet<FolderAuth> FolderAuth { get; set; }
        public virtual DbSet<FolderNode> FolderNode { get; set; }
        public virtual DbSet<AEPAdmin> AEPAdmin { get; set; }
        public virtual DbSet<DocDownloadLog> DocDownloadLog { get; set; }
        public virtual DbSet<Mail_Log> Mail_Log { get; set; }
        public virtual DbSet<DocHDownloadLog> DocHDownloadLog { get; set; }
        public virtual DbSet<DownloadLog> DownloadLog { get; set; }
        public virtual DbSet<MyFavorite> MyFavorite { get; set; }
    
        public virtual int GetDocID(string user, ObjectParameter docID)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocID", userParameter, docID);
        }
    }
}
