//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEP.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocRecord()
        {
            this.DocAlert = new HashSet<DocAlert>();
        }
    
        public string DocID { get; set; }
        public string DocName { get; set; }
        public Nullable<int> DocVersion { get; set; }
        public string PhysicalPath { get; set; }
        public Nullable<long> FolderID { get; set; }
        public Nullable<int> DocStatus { get; set; }
        public string CheckInBy { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public string CheckOutBy { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAlert> DocAlert { get; set; }
        public virtual FolderNode FolderNode { get; set; }
    }
}
