//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEP.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderAuth
    {
        public long AuthID { get; set; }
        public long FolderID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string UserAD { get; set; }
        public Nullable<int> FolderAuth1 { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual FolderNode FolderNode { get; set; }
        public virtual AEPGroup AEPGroup { get; set; }
    }
}
