//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEP.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FolderNode()
        {
            this.DocRecord = new HashSet<DocRecord>();
            this.FolderAuth = new HashSet<FolderAuth>();
        }
    
        public long FolderID { get; set; }
        public long ParentID { get; set; }
        public string FolderName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PhysicalPath { get; set; }
        public string FolderOwner { get; set; }
        public Nullable<bool> IsAuthInherit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocRecord> DocRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderAuth> FolderAuth { get; set; }
    }
}
